#! /bin/bash

#SETTING UP VARS

CURR_DIR=$(pwd)
LOGSTASH_VERSION="1.5.0"
LOGSTASH_DL_LINK="https://download.elastic.co/logstash/logstash/logstash-${LOGSTASH_VERSION}.tar.gz"
PYTHON_SCRIPT="$CURR_DIR/test_helper.py"

# CREATING TESTING DIRECTORY
mkdir ../logstash_test
cd ../logstash_test
TEST_DIR=$(pwd)

CONFIG0='
input{
    file{ 
        path => "'${TEST_DIR}'/input_files/*" 
        start_position => "beginning"
    }
}
filter{
    intervalmetric{
        counter => ["%{message}"]
        count_interval => 10
        add_tag => "im"
    }
}
output{
    if "im" in [tags]{
        file{
            path => "'${TEST_DIR}'/output_files/intervalmetrics.log"
            codec => "rubydebug"
        }
        stdout{
            codec => "rubydebug"
        }
    }

}
'

# Calling sudo early so it doesn't get burried by the stdout

cd $TEST_DIR
touch hi
sudo rm hi

# INSTALLING A PORTABLE LOGSTASH

cd $TEST_DIR
curl -O ${LOGSTASH_DL_LINK} 
tar -zxf logstash-${LOGSTASH_VERSION}.tar.gz
rm logstash-${LOGSTASH_VERSION}.tar.gz
mv logstash-${LOGSTASH_VERSION} logstash

# BUILDING FILTER INTO LOGSTASH

cd $CURR_DIR
gem build logstash-filter-intervalmetric.gemspec
$TEST_DIR/logstash/bin/plugin install logstash-filter-intervalmetric-*.gem

# RUNNING LOGSTASH

cd $TEST_DIR
mkdir input_files
mkdir output_files
echo "running: $CONFIG1"
logstash/bin/logstash -e "$CONFIG1" &
PID=$!
SLEEP_TIME=180
while true; do
    echo "one iter started"
    for i in $(seq 1 15); do
        python $PYTHON_SCRIPT generatefile "$TEST_DIR/input_files/$i.txt" "$RANDOM" 500000
        wc $TEST_DIR/input_files/$i.txt
    done
    sleep $SLEEP_TIME
    for i in $(seq 1 15); do
        > $TEST_DIR/input_files/$i.txt
        wc $TEST_DIR/input_files/$i.txt
    done
    if $(python $PYTHON_SCRIPT track $TEST_DIR/output_files/intervalmetrics.log); then
        ((SLEEP_TIME += 5))
    else
        ((SLEEP_TIME -= 5))
    fi
    echo $SLEEP_TIME
done

