#! /bin/bash

#SETTING UP VARS
. test_utils
FILTER_DIR=$(pwd)
LOGSTASH_VERSION="1.5.0"
LOGSTASH_DL_LINK="https://download.elastic.co/logstash/logstash/logstash-${LOGSTASH_VERSION}.tar.gz"
PYTHON_SCRIPT="$FILTER_DIR/test_helper.py"

# CREATING TESTING DIRECTORY
key=$RANDOM
mkdir ../logstash_test_$key
cd ../logstash_test_$key
TEST_DIR=$(pwd)

CONFIG0='
input{stdin{}}
filter{
    intervalmetric {}
}
output{stdout{}}
'
CONFIG1='
input{
    file{ 
        path => "'${TEST_DIR}'/input_files/*" 
        start_position => "beginning"
    }
}
filter{
    intervalmetric{
        counter => ["%{message}"]
        count_interval => 10
        add_tag => "im"
    }
    if "im" not in [tags]{
    metrics{
        meter => "%{message}"
        add_tag => "m"
        rates => []
        flush_interval => 5 
    }
    }
}
output{
    if "m" in [tags]{
        file{
            path => "'${TEST_DIR}'/output_files/metrics.log"
            codec => "rubydebug"
        }
    }
    if "im" in [tags]{
        file{
            path => "'${TEST_DIR}'/output_files/intervalmetrics.log"
            codec => "rubydebug"
        }
        stdout{}
   }
    
}
'

#echo $CONFIG1

# Calling sudo early so it doesn't get burried by the stdout

sudo cd $TEST_DIR

# INSTALLING A PORTABLE LOGSTASH

download_logstash $TEST_DIR

# BUILDING FILTER INTO LOGSTASH

install_IM_filter $TEST_DIR $FILTER_DIR

# CREATING FILES TO TEST

generate_input_files $TEST_DIR $PYTHON_SCRIPT 30 50000

# RUNNING LOGSTASH
run_logstash $TEST_DIR "$CONFIG1" 80
cat $TEST_DIR/output_files/*
python $PYTHON_SCRIPT compare $TEST_DIR/output_files/intervalmetrics.log $TEST_DIR/output_files/metrics.log
run_logstash $TEST_DIR "$CONFIG1" 120 
python $PYTHON_SCRIPT intervalmetric "$TEST_DIR/output_files/intervalmetrics.log"
#python $PYTHON_SCRIPT metric "$TEST_DIR/output_files/metrics.log"

# REMOVING CREATED FILES

clear_test_interval $TEST_DIR $FILTER_DIR 


