#! /bin/bash

#SETTING UP VARS

CURR_DIR=$(pwd)
LOGSTASH_VERSION="1.5.0"
LOGSTASH_DL_LINK="https://download.elastic.co/logstash/logstash/logstash-${LOGSTASH_VERSION}.tar.gz"
PYTHON_SCRIPT="$CURR_DIR/test_helper.py"

# CREATING TESTING DIRECTORY
mkdir ../logstash_test
cd ../logstash_test
TEST_DIR=$(pwd)

CONFIG0='
input{stdin{}}
filter{
    intervalmetric {}
}
output{stdout{}}
'
CONFIG1='
input{
    file{ 
        path => "'${TEST_DIR}'/input_files/*" 
        start_position => "beginning"
        delimiter => " "
    }
}
filter{
    intervalmetric{
        counter => "%{message}"
        count_interval => 30
        add_tag => "im"
    }
    metrics{
        meter => "%{message}"
        add_tag => "m"
        rates => []
        flush_interval => 35 
    }
}
output{
    if "m" in [tags]{
        file{
            path => "'${TEST_DIR}'/output_files/metrics"
            codec => "rubydebug"
        }
   }
    if "im" in [tags]{
        file{
            path => "'${TEST_DIR}'/output_files/intervalmetrics"
            codec => "rubydebug"
        }
        stdout{
            codec => "rubydebug"
        }
 
    }

}
'

#echo $CONFIG1

# Calling sudo early so it doesn't get burried by the stdout

cd $TEST_DIR
touch hi
sudo rm hi

# INSTALLING A PORTABLE LOGSTASH

cd $TEST_DIR
curl -O ${LOGSTASH_DL_LINK} 
tar -zxf logstash-${LOGSTASH_VERSION}.tar.gz
rm logstash-${LOGSTASH_VERSION}.tar.gz
mv logstash-${LOGSTASH_VERSION} logstash

# BUILDING FILTER INTO LOGSTASH

cd $CURR_DIR
gem build logstash-filter-intervalmetric.gemspec
$TEST_DIR/logstash/bin/plugin install logstash-filter-intervalmetric-*.gem


# CREATING FILES TO TEST

cd $TEST_DIR
mkdir input_files
for i in $(seq 1 10); do
    python $PYTHON_SCRIPT generatefile "$TEST_DIR/input_files/$i.txt" "$i" 50000
    wc $TEST_DIR/input_files/$i.txt
done

# RUNNING LOGSTASH

cd $TEST_DIR
mkdir output_files
echo "running: $CONFIG0"
logstash/bin/logstash -e "$CONFIG0" & 
echo "running: $CONFIG1"
logstash/bin/logstash -e "$CONFIG1" &
PID=$!
sleep 60
kill $PID
ls $TEST_DIR/output_files/
cat $TEST_DIR/output_files/*


# REMOVING CREATED FILES

cd $CURR_DIR
rm $CURR_DIR/*.gem
sudo rm -r $TEST_DIR
echo 'done'
