#! /bin/bash

LOGSTASH_VERSION="1.5.0"
LOGSTASH_DL_LINK="https://download.elastic.co/logstash/logstash/logstash-${LOGSTASH_VERSION}.tar.gz"

download_logstash() {
    TEST_DIR=$1
    cd $TEST_DIR
    curl -O ${LOGSTASH_DL_LINK} 
    tar -zxf logstash-${LOGSTASH_VERSION}.tar.gz
    rm logstash-${LOGSTASH_VERSION}.tar.gz
    mv logstash-${LOGSTASH_VERSION} logstash
}

install_IM_filter() {
    TEST_DIR=$1
    FILTER_DIR=$2
    cd $FILTER_DIR
    gem build logstash-filter-intervalmetric.gemspec
    $TEST_DIR/logstash/bin/plugin install logstash-filter-intervalmetric-*.gem
}

generate_input_files() {
    TEST_DIR=$1
    PYTHON_SCRIPT=$2
    NUM_FILES=$3
    NUM_MSGS=$4
    cd $TEST_DIR
    mkdir input_files
    for i in $(seq 1 $NUM_FILES); do
        python $PYTHON_SCRIPT generatefile "$TEST_DIR/input_files/$i.txt" $RANDOM $NUM_MSGS
        wc $TEST_DIR/input_files/$i.txt
    done
}

run_logstash() {
    TEST_DIR=$1
    CONFIG=$2
    RUNTIME=$3
    cd $TEST_DIR
    mkdir output_files
    echo $CONFIG
    logstash/bin/logstash -e "$CONFIG" &
    PID=$!
    sleep $RUNTIME
    kill $PID
    sleep 10
}

clear_test_interval() {
    TEST_DIR=$1
    FILTER_DIR=$2
    cd $FILTER_DIR
    rm $FILTER_DIR/*.gem
    sudo rm -r $TEST_DIR
    echo 'done'
}

