#! /bin/bash

LOGSTASH_VERSION="1.5.0"
LOGSTASH_DL_LINK="https://download.elastic.co/logstash/logstash/logstash-${LOGSTASH_VERSION}.tar.gz"

download_logstash() {
    TEST_DIR=$1
    cd $TEST_DIR
    curl -O ${LOGSTASH_DL_LINK} 
    tar -zxf logstash-${LOGSTASH_VERSION}.tar.gz
    rm logstash-${LOGSTASH_VERSION}.tar.gz
    mv logstash-${LOGSTASH_VERSION} logstash
}

install_IM_filter() {
    TEST_DIR=$1
    FILTER_DIR=$2
    cd $FILTER_DIR
    gem build logstash-filter-intervalmetric.gemspec
    $TEST_DIR/logstash/bin/plugin install logstash-filter-intervalmetric-*.gem
}

generate_input_files() {
    TEST_DIR=$1
    PYTHON_SCRIPT=$2
    NUM_FILES=$3
    NUM_MSGS=$4
    for i in $(seq 1 $NUM_FILES); do
        python $PYTHON_SCRIPT generatefile "$TEST_DIR/input_files/$i.txt" $RANDOM $NUM_MSGS
        wc $TEST_DIR/input_files/$i.txt
    done
}


